package com.damo.gestionDeStock.handlers.exception;

public enum ErrorCodes {

    ARTICLE_NOT_FOUND(1000),
    ARTICLE_NOT_VALID(1001),
    ARTICLE_ALREADY_IN_USE(1002),

    CATEGORY_NOT_FOUND(2000),
    CATEGORY_NOT_VALID(2001),
    CATEGORY_ALREADY_IN_USE(2002),
    //TODO complete the rest of the error codes

    CLIENT_NOT_FOUND(3000),
    CLIENT_NOT_VALID(3001),
    CLIENT_ALREADY_IN_USE(3002),
    ENTREPRISE_NOT_FOUND(4000),
    ENTREPRISE_NOT_VALID(4001),

    COMMANDE_CLIENT_NOT_FOUND(5000),
    COMMANDE_CLIENT_NON_MODIFIABLE(5001),
    COMMANDE_CLIENT_ALREADY_IN_USE(5002),
    COMMANDE_CLIENT_NOT_VALID(5003),

    COMMANDE_FOURNISSEUR_NOT_FOUND(6000),
    COMMANDE_FOURNISSEUR_NON_MODIFIABLE(6001),
    COMMANDE_FOURNISSEUR_NOT_VALID(6002),

    FOURNISSEUR_ALREADY_IN_USE(6002),
    FOURNISSEUR_NOT_VALID(6003),
    FOURNISSEUR_NOT_FOUND(6003),

    LIGNE_COMMANDE_CLIENT_NOT_FOUND(7000),
    LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND(8000),
    LIGNE_VENTE_NOT_FOUND(9000),
    MOUVE_STK_NOT_FOUND(10000),
    MVT_STK_NOT_VALID(10001),
    UTILISATEUR_NOT_FOUND(11000),
    USER_CHANGE_PASSWORD_OBJECT_NOT_VALID(11001),
    BAD_CREDENTIALS(11002),
    VENTE_NOT_FOUND(12000),
    VENTE_ALREADY_IN_USE(12001),

    //Liste des exceptions technique
    UPDATE_PHOTO_EXCEPTION(14000),
    UNKNOWN_CONTEXT(14001);

    private int code;

    ErrorCodes(int code) {
        this.code = code;
    }

    public int getCode() {
        return  code;
    }

}
